import { contextBridge, ipcRenderer } from "electron";
import type { OrbitAPI } from "../shared/contracts.js";

const api: OrbitAPI = {
  policies: () => ipcRenderer.invoke("orbit:policies"),
  systemSnapshot: () => ipcRenderer.invoke("orbit:system"),
  recentWork: () => ipcRenderer.invoke("orbit:recent"),
  findFiles: query => ipcRenderer.invoke("orbit:files:find", query),
  gitContext: () => ipcRenderer.invoke("orbit:git"),
  cleanupPlan: () => ipcRenderer.invoke("orbit:cleanup"),
  trash: paths => ipcRenderer.invoke("orbit:trash", paths),
  audit: () => ipcRenderer.invoke("orbit:audit"),
  indexKnowledge: () => ipcRenderer.invoke("orbit:knowledge:index"),
  searchKnowledge: query => ipcRenderer.invoke("orbit:knowledge:search", query),
  planCommand: command => ipcRenderer.invoke("orbit:command:plan", command),
  openPath: path => ipcRenderer.invoke("orbit:path:open", path),
  openFolder: folder => ipcRenderer.invoke("orbit:folder:open", folder),
  launchApplication: application => ipcRenderer.invoke("orbit:app:launch", application),
  macPermissions: () => ipcRenderer.invoke("orbit:mac:permissions"),
  macControl: request => ipcRenderer.invoke("orbit:mac:control", request),
  draftEmail: request => ipcRenderer.invoke("orbit:email:draft", request),
  conversationHistory: () => ipcRenderer.invoke("orbit:conversation:list"),
  appendConversation: turn => ipcRenderer.invoke("orbit:conversation:append", turn),
  clearConversation: () => ipcRenderer.invoke("orbit:conversation:clear"),
  githubWorkflow: repository => ipcRenderer.invoke("orbit:github:workflow", repository),
  browserNavigate: request => ipcRenderer.invoke("orbit:browser:navigate", request),
  liveInfo: request => ipcRenderer.invoke("orbit:live:info", request),
  youtubePlay: query => ipcRenderer.invoke("orbit:browser:youtube", query),
  amazonSearch: request => ipcRenderer.invoke("orbit:browser:amazon", request),
  describePage: () => ipcRenderer.invoke("orbit:browser:describe"),
  summarizePage: () => ipcRenderer.invoke("orbit:browser:summarize"),
  findOnPage: query => ipcRenderer.invoke("orbit:browser:find", query),
  research: query => ipcRenderer.invoke("orbit:web:research", query),
  batteryStatus: () => ipcRenderer.invoke("orbit:system:battery"),
  describeScreen: query => ipcRenderer.invoke("orbit:screen:describe", query),
  takeScreenshot: () => ipcRenderer.invoke("orbit:screen:capture"),
  startVoice: () => ipcRenderer.invoke("orbit:voice:start"),
  stopVoice: () => ipcRenderer.invoke("orbit:voice:stop"),
  stopSpeaking: () => ipcRenderer.invoke("orbit:speech:stop"),
  armVoice: () => ipcRenderer.invoke("orbit:voice:arm"),
  speak: text => ipcRenderer.invoke("orbit:voice:speak", text),
  onVoiceEvent: callback => { const listener = (_event: Electron.IpcRendererEvent, payload: Parameters<typeof callback>[0]) => callback(payload); ipcRenderer.on("orbit:voice:event", listener); return () => ipcRenderer.removeListener("orbit:voice:event", listener); },
  onVoiceCommand: callback => { const listener = (_event: Electron.IpcRendererEvent, command: string) => callback(command); ipcRenderer.on("orbit:voice:command", listener); return () => ipcRenderer.removeListener("orbit:voice:command", listener); },
  aiStatus: () => ipcRenderer.invoke("orbit:ai:status"),
  geminiStatus: () => ipcRenderer.invoke("orbit:gemini:status"),
  configureGemini: apiKey => ipcRenderer.invoke("orbit:gemini:configure", apiKey),
  setGeminiBudget: monthlyBudgetUsd => ipcRenderer.invoke("orbit:gemini:budget", monthlyBudgetUsd),
  orbitPlayStart: mode => ipcRenderer.invoke("orbit:play:start", mode),
  orbitPlayStop: () => ipcRenderer.invoke("orbit:play:stop"),
  orbitPlayAction: gesture => ipcRenderer.invoke("orbit:play:action", gesture),
};
contextBridge.exposeInMainWorld("orbit", api);
