import { contextBridge, ipcRenderer } from "electron";
import type { OrbitAPI } from "../shared/contracts.js";

const api: OrbitAPI = {
  policies: () => ipcRenderer.invoke("orbit:policies"),
  systemSnapshot: () => ipcRenderer.invoke("orbit:system"),
  recentWork: () => ipcRenderer.invoke("orbit:recent"),
  gitContext: () => ipcRenderer.invoke("orbit:git"),
  cleanupPlan: () => ipcRenderer.invoke("orbit:cleanup"),
  trash: paths => ipcRenderer.invoke("orbit:trash", paths),
  audit: () => ipcRenderer.invoke("orbit:audit"),
  indexKnowledge: () => ipcRenderer.invoke("orbit:knowledge:index"),
  searchKnowledge: query => ipcRenderer.invoke("orbit:knowledge:search", query),
  planCommand: command => ipcRenderer.invoke("orbit:command:plan", command),
  openPath: path => ipcRenderer.invoke("orbit:path:open", path),
  openFolder: folder => ipcRenderer.invoke("orbit:folder:open", folder),
  launchApplication: application => ipcRenderer.invoke("orbit:app:launch", application),
  githubWorkflow: repository => ipcRenderer.invoke("orbit:github:workflow", repository),
  browserNavigate: request => ipcRenderer.invoke("orbit:browser:navigate", request),
  liveWeather: query => ipcRenderer.invoke("orbit:live:weather", query),
  liveNews: query => ipcRenderer.invoke("orbit:live:news", query),
  liveCricket: () => ipcRenderer.invoke("orbit:live:cricket"),
  research: query => ipcRenderer.invoke("orbit:web:research", query),
  batteryStatus: () => ipcRenderer.invoke("orbit:system:battery"),
  describeScreen: query => ipcRenderer.invoke("orbit:screen:describe", query),
  startVoice: () => ipcRenderer.invoke("orbit:voice:start"),
  stopVoice: () => ipcRenderer.invoke("orbit:voice:stop"),
  stopSpeaking: () => ipcRenderer.invoke("orbit:speech:stop"),
  armVoice: () => ipcRenderer.invoke("orbit:voice:arm"),
  speak: text => ipcRenderer.invoke("orbit:voice:speak", text),
  onVoiceEvent: callback => { const listener = (_event: Electron.IpcRendererEvent, payload: Parameters<typeof callback>[0]) => callback(payload); ipcRenderer.on("orbit:voice:event", listener); return () => ipcRenderer.removeListener("orbit:voice:event", listener); },
  onVoiceCommand: callback => { const listener = (_event: Electron.IpcRendererEvent, command: string) => callback(command); ipcRenderer.on("orbit:voice:command", listener); return () => ipcRenderer.removeListener("orbit:voice:command", listener); },
  aiStatus: () => ipcRenderer.invoke("orbit:ai:status"),
  geminiStatus: () => ipcRenderer.invoke("orbit:gemini:status"),
  configureGemini: apiKey => ipcRenderer.invoke("orbit:gemini:configure", apiKey),
  setGeminiBudget: monthlyBudgetUsd => ipcRenderer.invoke("orbit:gemini:budget", monthlyBudgetUsd),
};
contextBridge.exposeInMainWorld("orbit", api);
