import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { createPortal } from "react-dom";
import type { AIStatus, AuditEvent, CleanupCandidate, GitContext, RecentItem, SearchHit, SystemSnapshot } from "../shared/contracts";
import "./style.css";
import "./wake.css";
import "./product.css";
import "./voice.css";
import "./ai.css";
import "./command-deck.css";

type View = "system"|"recent"|"knowledge"|"git"|"cleanup"|"audit"|"settings";
const fmt=(bytes:number)=>bytes>1024**3?`${(bytes/1024**3).toFixed(1)} GB`:`${Math.round(bytes/1024**2)} MB`;
const ago=(date:string|number)=>new Intl.RelativeTimeFormat("en",{numeric:"auto"}).format(Math.round((new Date(date).getTime()-Date.now())/86400000),"day");
const titles:Record<View,string>={system:"Your computer, understood.",recent:"Resume your work",knowledge:"Search your private context",git:"Developer context",cleanup:"Safe cleanup plan",audit:"Action history",settings:"Orbit intelligence"};

function App(){
  const [view,setView]=useState<View>("system"),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const [system,setSystem]=useState<SystemSnapshot|null>(null),[recent,setRecent]=useState<RecentItem[]>([]),[repos,setRepos]=useState<GitContext[]>([]),[cleanup,setCleanup]=useState<CleanupCandidate[]>([]),[events,setEvents]=useState<AuditEvent[]>([]);
  const [selected,setSelected]=useState<string[]>([]),[command,setCommand]=useState(""),[query,setQuery]=useState(""),[hits,setHits]=useState<SearchHit[]>([]),[indexStatus,setIndexStatus]=useState("No folder indexed in this session."),[notice,setNotice]=useState("");
  const [ai,setAI]=useState<AIStatus|null>(null);
  const guard=async(action:()=>Promise<void>)=>{setBusy(true);setError("");try{await action()}catch(reason){setError(reason instanceof Error?reason.message:"Orbit could not complete that action.");await window.orbit.speak("Boss, I hit an error while completing that. Would you like me to brief you?")}finally{setBusy(false)}};
  const load=(next:View)=>guard(async()=>{setView(next);if(next==="system")setSystem(await window.orbit.systemSnapshot());if(next==="recent")setRecent(await window.orbit.recentWork());if(next==="git")setRepos(await window.orbit.gitContext());if(next==="cleanup")setCleanup(await window.orbit.cleanupPlan());if(next==="audit")setEvents(await window.orbit.audit());if(next==="settings")setAI(await window.orbit.aiStatus())});
  const executeText=(input:string)=>guard(async()=>{if(!input.trim())return;setNotice("");const plan=await window.orbit.planCommand(input);if(plan.intent==="unknown"){const message="Boss, I couldn't safely map that request. Would you like help rephrasing it?";setError(message);await window.orbit.speak(message);return}setCommand("");if(plan.intent==="answer"||plan.intent==="clarify"){const reply=plan.reply||plan.explanation;setNotice(reply);await window.orbit.speak(reply);return}const githubRequest=/\b(github|git hub|get hub|gethub)\b/i.test(input);if(plan.intent==="github"||(plan.intent==="launch"&&plan.application==="Google Chrome"&&githubRequest)){const result=await window.orbit.githubWorkflow(plan.repository);setNotice(result.summary);await window.orbit.speak(result.summary);return}if(plan.intent==="browser"){const result=await window.orbit.browserNavigate({url:plan.url,query:plan.query});setNotice(result.summary);await window.orbit.speak(result.summary);return}if(plan.intent==="launch"){if(!plan.application)throw new Error("Orbit could not identify the requested application");const reply=plan.reply||`Opening ${plan.application}`;await window.orbit.speak(reply);const result=await window.orbit.launchApplication(plan.application);setNotice(result.launched?`${result.application} opened.`:"Application could not be opened.");return}if(plan.intent==="knowledge"){setView("knowledge");setQuery(plan.query||"");setHits((await window.orbit.searchKnowledge(plan.query||"")).hits);await window.orbit.speak(plan.reply||"I found the most relevant local results.");return}await window.orbit.speak(plan.reply||(plan.intent==="system"?"Opening your live system diagnostics.":`Opening ${plan.intent}.`));await load(plan.intent)});
  useEffect(()=>{void load("system");const stopEvents=window.orbit.onVoiceEvent(event=>{if(event.type==="partial"&&event.text)setCommand(event.text)});const stopCommands=window.orbit.onVoiceCommand(value=>{setCommand(value);void executeText(value)});void window.orbit.startVoice();return()=>{stopEvents();stopCommands()}},[]);
  const execute=()=>executeText(command);
  const index=()=>guard(async()=>{const result=await window.orbit.indexKnowledge();setIndexStatus(result.cancelled?"Folder selection cancelled.":`Indexed ${result.indexed} files locally; skipped ${result.skipped}.`)});
  const search=()=>guard(async()=>setHits((await window.orbit.searchKnowledge(query)).hits));
  const trash=()=>guard(async()=>{if(!selected.length||!confirm(`Move ${selected.length} selected file(s) to Trash?`))return;const result=await window.orbit.trash(selected);setSelected([]);setIndexStatus(`${result.moved.length} moved to Trash; ${result.failed.length} failed.`);setCleanup(await window.orbit.cleanupPlan())});
  const nav:[View,string][]=[["system","System"],["recent","Recent work"],["knowledge","Local knowledge"],["git","Repositories"],["cleanup","Safe cleanup"],["audit","Action history"],["settings","Settings"]];
  return <main><aside><div className="brand"><i>O</i><span><b>Orbit</b><small>Local operating layer</small></span></div><nav>{nav.map(([id,label])=><button className={view===id?"active":""} onClick={()=>void load(id)} key={id}>{label}</button>)}</nav><VoiceConsole/><div className="privacy"><span>● {ai?.available?"Local AI ready":"Local mode"}</span><small>$0 usage · data stays on this Mac</small></div></aside><section className="content"><header><div><small>ORBIT / COMMAND DECK</small><h1>{titles[view]}</h1></div><b className={busy?"pulse":""}>{busy?"Thinking…":"System online"}</b></header><div className="command"><span>⌘</span><input value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void execute()} placeholder="What would you like Orbit to do, boss?"/><button onClick={()=>void execute()}>Run</button></div>{error&&<div className="error"><b>Orbit paused safely.</b><span>{error}</span><button onClick={()=>setError("")}>Dismiss</button></div>}{notice&&<div className="ai-reply"><i>O</i><span>{notice}</span><button onClick={()=>setNotice("")}>×</button></div>}{view==="system"&&<System data={system}/>} {view==="recent"&&<Recent items={recent}/>} {view==="knowledge"&&<Knowledge query={query} setQuery={setQuery} hits={hits} status={indexStatus} index={index} search={search}/>} {view==="git"&&<Repos items={repos}/>} {view==="cleanup"&&<Cleanup items={cleanup} selected={selected} setSelected={setSelected} trash={trash}/>} {view==="audit"&&<Audit items={events}/>} {view==="settings"&&<Settings ai={ai} refresh={()=>void load("settings")}/>}</section></main>
}

function Settings({ai,refresh}:{ai:AIStatus|null;refresh:()=>void}){const ready=Boolean(ai?.available);return <div className="settings-grid"><article className="ai-card"><small>OLLAMA · LOCAL AI · {ai?.cost||"$0"}</small><h2>{ready?"Orbit Intelligence is ready":ai?.running?"Install the local model":"Start Ollama"}</h2><p>{ready?`${ai?.model} is running completely on this Mac. There are no API charges or usage limits.`:ai?.running?"Ollama is running, but Orbit's model has not been downloaded yet.":"Install and open Ollama once. Orbit talks only to its local service at 127.0.0.1."}</p><div className="setup-command"><code>{ai?.running?ai.installCommand:"Download from ollama.com, then open Ollama"}</code><button onClick={refresh}>Check again</button></div><small className="setup-note">Run the model command once in Terminal. Future Orbit updates reuse the same download.</small></article><article className="trust-card"><small>TRUST BOUNDARY</small><h3>Private and constrained.</h3><p>The local model interprets your request. Orbit executes only reviewed local tools—never arbitrary shell commands. Cleanup still requires approval.</p><ul><li>No cloud AI provider</li><li>No API key or billing</li><li>Short in-memory conversation</li><li>Typed structured responses</li></ul></article></div>}

function System({data}:{data:SystemSnapshot|null}){if(!data)return <Empty/>;return <><CommandCore data={data}/><div className="hero"><div><small>ORBIT DIAGNOSIS</small><h2>{data.memory.usedPct>85?"Memory pressure needs attention.":data.cpuUsagePct>80?"CPU usage is elevated.":"Your system looks healthy."}</h2><p>Captured locally at {new Date(data.capturedAt).toLocaleTimeString()}. Orbit has not modified anything.</p></div><span>{data.platform}</span></div><div className="metrics"><Metric label="CPU" value={`${data.cpuUsagePct}%`} sub={data.cpuModel}/><Metric label="Memory" value={`${data.memory.usedPct}%`} sub={`${data.memory.usedGb} of ${data.memory.totalGb} GB`}/><Metric label="Uptime" value={`${data.uptimeHours}h`} sub={data.hostname}/></div><article><h3>Storage volumes</h3>{data.storage.length?data.storage.map(volume=><div className="row" key={volume.mount}><b>{volume.mount}</b><span>{volume.usedGb} GB used of {volume.totalGb} GB</span><em>{volume.usedPct}% used</em></div>):<div className="empty">Storage information is unavailable.</div>}</article><article><h3>Highest resource processes</h3>{data.processes.map(p=><div className="row" key={p.pid}><b>{p.name}</b><span>PID {p.pid}</span><em>{p.cpuPct}% CPU · {p.memoryPct}% RAM</em></div>)}</article></>}
function CommandCore({data}:{data:SystemSnapshot}){return <section className="command-core"><div className="core-copy"><small>ORBIT INTELLIGENCE</small><h2>At your service, boss.</h2><p>Local reasoning online. Your private command deck is standing by.</p><div className="core-signal">{Array.from({length:31},(_,i)=><i key={i}/>)}</div></div><div className="core-stage"><div className="orbit-trail trail-a"/><div className="orbit-trail trail-b"/><div className="orbit-trail trail-c"/><div className="core-orb"><span>O</span></div><i className="satellite s1"/><i className="satellite s2"/><i className="satellite s3"/></div><div className="core-telemetry"><span><small>CPU</small><b>{data.cpuUsagePct}%</b></span><span><small>MEMORY</small><b>{data.memory.usedPct}%</b></span><span><small>MODE</small><b>LOCAL</b></span></div></section>}
function Metric({label,value,sub}:{label:string;value:string;sub:string}){return <article className="metric"><small>{label}</small><strong>{value}</strong><span>{sub}</span></article>}
function Recent({items}:{items:RecentItem[]}){return <article><h3>Recently modified files</h3>{items.length?items.map(x=><button className="row action-row" onClick={()=>void window.orbit.openPath(x.path)} key={x.path}><b>{x.name}</b><span>{x.kind.toUpperCase()} · {fmt(x.sizeBytes)}</span><em>{ago(x.modifiedAt)}</em></button>):<Empty/>}</article>}
function Knowledge({query,setQuery,hits,status,index,search}:{query:string;setQuery:(v:string)=>void;hits:SearchHit[];status:string;index:()=>void;search:()=>void}){return <><div className="notice knowledge-note"><div><b>Permission-scoped local search</b><span>{status}</span></div><button onClick={index}>Choose folder</button></div><div className="command knowledge-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="Search indexed notes and source files"/><button onClick={search}>Search</button></div><div className="cards">{hits.length?hits.map(hit=><article className="repo hit" key={hit.path}><small>{Math.round(hit.score*100)}% LOCAL MATCH</small><h3>{hit.title}</h3><p>{hit.excerpt}</p><button onClick={()=>void window.orbit.openPath(hit.path)}>Open cited file</button></article>):<Empty/>}</div></>}
function Repos({items}:{items:GitContext[]}){return <div className="cards">{items.length?items.map(x=><article className="repo" key={x.path}><small>{x.branch}</small><h3>{x.path.split("/").at(-1)}</h3><p>{x.lastCommit}</p><span>{x.status.length?`${x.status.length} uncommitted change(s)`:"Clean working tree"}</span></article>):<Empty/>}</div>}
function Cleanup({items,selected,setSelected,trash}:{items:CleanupCandidate[];selected:string[];setSelected:(x:string[])=>void;trash:()=>void}){const total=items.filter(x=>selected.includes(x.path)).reduce((sum,x)=>sum+x.sizeBytes,0);return <><div className="notice"><b>Dry-run only</b><span>Nothing moves until you select files and approve the final action.</span><button disabled={!selected.length} onClick={trash}>Move {selected.length} to Trash · {fmt(total)}</button></div><article>{items.length?items.map(x=><label className="row selectable" key={x.path}><input type="checkbox" checked={selected.includes(x.path)} onChange={e=>setSelected(e.target.checked?[...selected,x.path]:selected.filter(p=>p!==x.path))}/><b>{x.name}</b><span>{x.reason}</span><em>{fmt(x.sizeBytes)}</em></label>):<Empty/>}</article></>}
function Audit({items}:{items:AuditEvent[]}){return <article><h3>Auditable tool activity</h3>{items.length?items.map(x=><div className="row" key={x.id}><b>{x.tool}</b><span className={`risk ${x.risk}`}>{x.risk}</span><span>{x.status}</span><em>{new Date(x.at).toLocaleString()}</em></div>):<Empty/>}</article>}
function VoiceConsole(){const [awake,setAwake]=useState(false),[voice,setVoice]=useState(true),[status,setStatus]=useState("Voice starting…");useEffect(()=>window.orbit.onVoiceEvent(event=>{if(event.type==="ready")setStatus(event.mode==="wake-word"?"Say “Hey Orbit”":"Voice ready");if(event.type==="wake"||event.type==="listening"){setAwake(true);setStatus("Listening for your command…")};if(event.type==="command"){setStatus("Working on it…");setTimeout(()=>setAwake(false),500)};if(event.type==="partial"&&event.text)setStatus(`Hearing: ${event.text}`);if(event.type==="stopped"){setAwake(false);setStatus("Microphone off")};if(event.type==="error"||event.type==="unavailable")setStatus(event.message||"Voice unavailable")}),[]);useEffect(()=>{const dismiss=(event:KeyboardEvent)=>{if(event.key==="Escape")setAwake(false)};window.addEventListener("keydown",dismiss);return()=>window.removeEventListener("keydown",dismiss)},[]);const wake=async()=>{setAwake(true);if(!voice){await window.orbit.startVoice();setVoice(true)}await window.orbit.armVoice()};const toggle=async()=>{if(voice){await window.orbit.stopVoice();setVoice(false)}else{await window.orbit.startVoice();setVoice(true)}};const scene=awake?createPortal(<div className="wake-scene" role="dialog" aria-modal="true"><div className="stars"/><button className="wake-close" onClick={()=>setAwake(false)}>ESC&nbsp;&nbsp;Dismiss</button><div className="wake-copy"><small>ORBIT / LOCAL INTELLIGENCE</small><h2>At your service, boss.</h2><p>{status}</p></div><div className="orbit-stage"><div className="halo h1"/><div className="halo h2"/><div className="halo h3"/><div className="orb"><div className="orb-core"/><div className="orb-shine"/></div><div className="voice-bars">{Array.from({length:17},(_,i)=><i key={i}/>)}</div></div><div className="wake-stats"><span><small>SYSTEM</small><b>ONLINE</b></span><span><small>POLICY</small><b>ENFORCED</b></span><span><small>PRIVACY</small><b>LOCAL ONLY</b></span></div><div className="wake-hint">Press Esc to dismiss</div></div>,document.body):null;return <><div className="voice-console"><small>VOICE CONSOLE</small><div className="voice-console-actions"><button onClick={()=>void wake()}><span>◉</span> Wake Orbit</button><button className={voice?"mic-live":"mic-off"} onClick={()=>void toggle()}>{voice?"Mic on":"Mic off"}</button></div><div className="voice-console-status"><span>◉</span><div><b>{status}</b><small>Say “Hey Orbit” · ⌘⇧Space</small></div></div></div>{scene}</>}
function Empty(){return <div className="empty">No local results yet.</div>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
